server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: whale-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni
    username: root
    password: 725616
mybatis-plus:
  configuration:
    # 在映射实体或者属性时候，将照数据库的表名和字段名中的下滑线去掉按照驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键生成策略
      id-type: ASSIGN_ID


